#!/bin/bash
apt update
apt install -y curl openssh-server ca-certificates tzdata perl
apt install -y postfix
curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash
EXTERNAL_URL="https://gitlab.${_SANDBOX_ID}.instruqt.io" apt install gitlab-ee