version: "3"
containers:
- name: aws-console
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  ports:
  - 80
  memory: 1024
virtualbrowsers:
- name: gitlab-site
  url: https://gitlab.${_SANDBOX_ID}.instruqt.io/
virtualmachines:
- name: gitlab
  image: ubuntu-os-cloud/ubuntu-2204-lts
  shell: /bin/bash
  machine_type: n1-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
aws_accounts:
- name: gitlab-aws
  managed_policies:
  - arn:aws:iam::aws:policy/AdministratorAccess
